name: Some testing pipeline

env:
  GO_VERSION: '1.21.0'

on:
  push:
  workflow_dispatch:

jobs:
  linter:
    name: linter 🧹
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.1
  unit-tests:
    name: unit tests 🚨
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}
          cache: false
      - name: execute tests
        run: go test ./...